CREATE Table BASE_DM.usuarios (id_usuario INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
nombre VARCHAR(255) NOT NULL, 
apellido_p VARCHAR(255) NOT NULL,
apellido_m VARCHAR(255) NOT NULL,
correo VARCHAR(255) NOT NULL,
contraseña VARCHAR(255) NOT NULL,
fech_nac DATE NOT NULL, 
genero VARCHAR(255) NOT NULL) ENGINE = INNODB;